export const FETCH_LOCATION_KEY_SUCCESS = 'FETCH_LOCATION_KEY_SUCCESS';
export const FETCH_LOCATION_KEY_FAIL = 'FETCH_LOCATION_KEY_FAIL';

export const FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';