export const FETCH_LOCATION_KEY_START = 'FETCH_LOCATION_KEY_START';
export const FETCH_LOCATION_KEY_SUCCESS = 'FETCH_LOCATION_KEY_SUCCESS';
export const FETCH_LOCATION_KEY_FAIL = 'FETCH_LOCATION_KEY_FAIL';

export const FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSED = 'SIDEBAR_CLOSED';

export const FETCH_HOURLY_DATA_START = 'FETCH_HOURLY_DATA_START';
export const FETCH_HOURLY_DATA_SUCCESS = 'FETCH_HOURLY_DATA_SUCCESS';
export const FETCH_HOURLY_DATA_FAIL = 'FETCH_HOURLY_DATA_FAIL';
